server:
  port: 9002

spring:
  application:
    name: verifier
  ssl:
    bundle:
      pem:
        verifier-signing:
          keystore:
            certificate: classpath:verifier_cert.pem
            private-key: classpath:verifier_key.pem

logging:
  level:
    dev.kmandalas.verifier: DEBUG

app:
  request-uri-store: http://${LOCAL_IP:localhost}:9002/verifier/request-object/
  deep-link-prefix: openid4vp://?client_id=verifier-backend.eudiw.cgn&request_uri=
  trusted-issuers:
    - http://${LOCAL_IP:localhost}:8080
  response-uri: http://${LOCAL_IP:localhost}:9002/verifier/verify-vp
  status-check-enabled: true
  client-metadata:
    client-name: Demo Verifier Inc.
    logo-uri: https://img.freepik.com/premium-vector/creative-logo-design-real-estate-company-vector-illustration_1253202-20005.jpg?semt=ais_hybrid&w=120
    purpose: Verify your Portable Document A1 credentials
  trust-validator:
    enabled: true
    url: http://localhost:8090
    vct-to-context:
      "urn:eu.europa.ec.eudi:pda1:1": PID
      "urn:eudi:pid:1": PID
    default-context: QEAA

---
spring:
  config:
    activate:
      on-profile: cloud

app:
  request-uri-store: https://vp-verifier.onrender.com/verifier/request-object/
  deep-link-prefix: openid4vp://?client_id=verifier-backend.eudiw.cgn&request_uri=
  trusted-issuers:
    - https://vc-issuer.onrender.com
  response-uri: https://vp-verifier.onrender.com/verifier/verify-vp
  status-check-enabled: true
  trust-validator:
    enabled: false
    url: http://localhost:8090
    vct-to-context:
      "urn:eu.europa.ec.eudi:pda1:1": PID
      "urn:eudi:pid:1": PID
    default-context: QEAA